use_frameworks!

target 'FLKAutoLayout_Example' do
  pod 'FLKAutoLayout', :path => '../'
 
  target 'FLKAutoLayout_Tests' do
    inherit! :search_paths
  
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
